title: franz.media - Franz Krekeler personal website
email: fkrekeler+fm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Seit 2016 Bachelor Student in Mensch-Computer-Interaktion an der Uni Hamburg.
  Vorher Videoredakteur bei Spiegel Online für bento. Leidenschaft für Datenanalyse und Datenbanken.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: franz.media # add your name
author-pic: adam-face.jpg
about-author: My name is Adam Neilson. I’m a full-time adventure travel blogger and photographer who’s been exploring the world for over 2 years.

# Contact links
email: fkrekeler+fm@gmail.com# Add your Email address
phone: # Add your Phone number
website: # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: franz101 # Add your Github handle
twitter: '@filmfranz' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: '@franzfilm' # Add your Instagram handle
pinterest: # Add your Pinterest handle
collections:
  shop:
    output: true
    permalink: "/:collection/:title/"
  #data_advent
# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
